Write-Host "京东iPhone 16搜索页面已打开"
Write-Host "页面地址: https://search.jd.com/Search?keyword=iPhone%2016&enc=utf-8&psort=3"
Write-Host ""
Write-Host "请手动操作:"
Write-Host "1. 查看Chrome中打开的页面"
Write-Host "2. 第一个商品就是最便宜的iPhone 16"
Write-Host "3. 右键点击商品 -> 复制链接地址"
Write-Host "4. 将链接粘贴给我"
Write-Host ""
Write-Host "或者，如果你看到链接，可以直接告诉我"